<?php
define("HOST_NAME","localhost");
define("DB_USER","root");
define("DB_PASS","");
define("DB_NAME","phonebook");
define("DB_CONTACTS","contact");
define("DB_GROUP","groupType");
define("DB_PHONETYPE","phoneType");
define("DB_USERS","user");
define("DB_INFO","information");
define("DB_TYPE","infoType");
?>